
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: konvert
      MYSQL_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: bckend
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"
    command: pnpm run start:prod

volumes:
  db_data: